### ISSUE TITLE
Hammerjs 2.0.4

### ISSUE THREAD

**Issue by AdrienMoretti** [vincent-pochet/hammerjs-rails#3]
Hi Vincent, 

I stumbled upon your gem and noticed it was not up-to-date. 
Will you have the time to update it?

**Comment by kirantpatil** [comment]
Yes, any updates ?

**Comment by vincent-pochet** [comment]
Hi,

Thanks to @tijn it is now up-to-date!

https://github.com/vincent-pochet/hammerjs-rails/pull/4
