### ISSUE TITLE
Are the included plugins out of date?

### ISSUE THREAD

**Issue by meowsus** [vincent-pochet/hammerjs-rails#7]
I see that this project includes these additional plugins:
- hammer.fakemultitouch.js
- hammer.showtouches.js

which seem to have been pilfered from this page:
https://github.com/hammerjs/hammer.js/wiki/Plugins

However the links on this wiki page are dead and indicate that they were compatible with v1.x. I haven't loaded it up, but it seems like these plugins are pretty unsupported.

Hammer.js docs show there is a new plugin listed called "touch emulator" which might be a replacement for the fake multitouch plugin:
http://hammerjs.github.io/touch-emulator/

I can open up a PR to remove these plugins and replace it with the touch emulator plugin, if you'd like. 

I just wanted to open a dialogue about it before doing so.

**Comment by vincent-pochet** [comment]
@meowsus thank you for checking these plugins.
Indeed if they are out of date and unsupported, I think we should remove them
Ok for a new PR :+1:
